#!/usr/bin/env bash

USER="sampleWriter"
PASS="sampleWriter"
keytabDirLocation="/home/ec2-user/keytab"

if [[ -f $keytabDirLocation/$USER.keytab ]]
then
  rm $keytabDirLocation/$USER.keytab
fi

printf "%b" "addent -password -p $USER@neo4j.com -k 1 -e aes256-cts-hmac-sha1-96\n$PASS\nwrite_kt $keytabDirLocation/$USER.keytab" | ktutil
printf "%b" "addent -password -p $USER@neo4j.com -k 1 -e des3-cbc-sha1-kd\n$PASS\nwrite_kt $keytabDirLocation/$USER.keytab" | ktutil
printf "%b" "addent -password -p $USER@neo4j.com -k 1 -e arcfour-hmac-md5\n$PASS\nwrite_kt $keytabDirLocation/$USER.keytab" | ktutil
printf "%b" "addent -password -p $USER@neo4j.com -k 1 -e des-hmac-sha1\n$PASS\nwrite_kt $keytabDirLocation/$USER.keytab" | ktutil
printf "%b" "addent -password -p $USER@neo4j.com -k 1 -e des-cbc-md5\n$PASS\nwrite_kt $keytabDirLocation/$USER.keytab" | ktutil
printf "%b" "addent -password -p $USER@neo4j.com -k 1 -e des-cbc-md4\n$PASS\nwrite_kt $keytabDirLocation/$USER.keytab" | ktutil

printf "%b" "read_kt $keytabDirLocation/$USER.keytab\nlist" | ktutil

echo ""

exit $?