#!/usr/bin/env bash

sudo yum -y update
sudo yum -y install ruby wget

cd /home/ec2-user
wget https://aws-codedeploy-eu-west-2.s3.amazonaws.com/latest/install
chmod +x ./install
sudo ./install auto
sudo service codedeploy-agent status